### PR TITLE
Create appleIdHashedPassword and update xapsd.yaml

### PR DESCRIPTION
**Pull request by gitze**
This small helper script will create the appleIdHashedPassword (without the need of pressing CTRL-D twice) and update the config file xapsd.yaml automatically.

### CODE REVIEW

**Comment by freswa** [comment]
Could you integrate this into the xapsd binary please?

**Comment by gitze** [comment]
This is a shell script which is used only during initial setup of the configuration. Sorry, I'm not familiar with "go" and can't integrate this functionality into the xapsd binary

**Comment by gitze** [comment]
dropping the shell script in favor for a command line tool in go

**Comment by freswa** [comment]
Do you want to open another PR? Otherwise I'd happy to implement your hash function as a cmd line parameter ;)

**Pull request closed without merging**
